---
- name: Copy the smokeping_prober systemd service file
  ansible.builtin.template:
    src: smokeping_prober.service.j2
    dest: /etc/systemd/system/smokeping_prober.service
    owner: root
    group: root
    mode: 0644
  notify: restart smokeping_prober

- name: Create smokeping_prober config directory
  ansible.builtin.file:
    path: "/etc/smokeping_prober"
    state: directory
    owner: root
    group: root
    mode: u+rwX,g+rwX,o=rX

- name: Copy the smokeping_prober web config file
  ansible.builtin.template:
    src: web_config.yaml.j2
    dest: /etc/smokeping_prober/web_config.yaml
    owner: root
    group: root
    mode: 0644
  notify: restart smokeping_prober

- name: Copy the smokeping_prober target config file
  ansible.builtin.template:
    src: config.yaml.j2
    dest: /etc/smokeping_prober/config.yaml
    owner: root
    group: root
    mode: 0644
  notify: restart smokeping_prober

- name: Allow smokeping_prober port in SELinux on RedHat OS family
  community.general.seport:
    ports: "{{ smokeping_prober_web_listen_address.split(':')[-1] }}"
    proto: tcp
    setype: http_port_t
    state: present
  when:
    - ansible_version.full is version_compare('2.4', '>=')
    - ansible_selinux.status == "enabled"
